using ABlueRainbowBackend.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace ABlueRainbowBackend.Data
{
    public static class DbInitializer
    {
        public static void Initialize(ApplicationDbContext context, IConfiguration configuration)
        {
            context.Database.EnsureCreated();
            EnsureAdminUsersTable(context);
            EnsureAdminAuditLogsTable(context);
            SeedAdminUser(context, configuration);

            // Seeding providers
            if (!context.Providers.Any())
            {
                var providers = new Provider[]
                {
                    new Provider { Id = 1, FacilityType = "Assisted Living", FacilityName = "Assisted Living Provider" },
                    new Provider { Id = 2, FacilityType = "Home Health", FacilityName = "Home Health Provider" },
                    new Provider { Id = 3, FacilityType = "Hospice", FacilityName = "Hospice Provider" },
                    new Provider { Id = 4, FacilityType = "Skilled Nursing", FacilityName = "Skilled Nursing Provider" }
                };

                foreach (var p in providers)
                {
                    context.Providers.Add(p);
                }
                context.SaveChanges();
            }

            var alProvId = 1;
            var hhProvId = 2;
            var hospProvId = 3;
            var snfProvId = 4;

            if (!context.AssistedLivingFacilities.Any())
            {
                for (int i = 1; i <= 14; i++)
                {
                    context.AssistedLivingFacilities.Add(new AssistedLivingFacility
                    {
                        Name = $"Golden Years {i}",
                        Address = $"{123 + i} Sunset Blvd",
                        City = "Los Angeles",
                        State = "CA",
                        ZipCode = $"9000{i % 10}",
                        PhoneNumber = $"555-01{i:02}",
                        ProviderId = alProvId
                    });
                }
            }

            context.HomeHealthFacilities.Add(new HomeHealthFacility
            {
                Name = "Care at Home",
                Address = "456 Hill St",
                City = "San Francisco",
                State = "CA",
                ZipCode = "94101",
                PhoneNumber = "555-0102",
                ProviderId = hhProvId
            });

            context.HospiceFacilities.Add(new HospiceFacility
            {
                Name = "Peaceful Journey",
                Address = "789 Valley Ln",
                City = "San Diego",
                State = "CA",
                ZipCode = "92101",
                PhoneNumber = "555-0103",
                ProviderId = hospProvId
            });

            context.SkilledNursingFacilities.Add(new SkilledNursingFacility
            {
                Name = "Recovery Center",
                Address = "321 Oak Way",
                City = "Sacramento",
                State = "CA",
                ZipCode = "95814",
                PhoneNumber = "555-0104",
                ProviderId = snfProvId
            });

            context.SaveChanges();
        }

        private static void SeedAdminUser(ApplicationDbContext context, IConfiguration configuration)
        {
            if (context.AdminUsers.Any())
            {
                return;
            }

            var username = configuration["Authentication:AdminUsername"];
            var password = configuration["Authentication:AdminPassword"];

            if (string.IsNullOrWhiteSpace(username) || string.IsNullOrWhiteSpace(password))
            {
                return;
            }

            var adminUser = new AdminUser
            {
                Username = username,
                DisplayName = "Primary Admin",
                IsActive = true,
            };

            var passwordHasher = new PasswordHasher<AdminUser>();
            adminUser.PasswordHash = passwordHasher.HashPassword(adminUser, password);

            context.AdminUsers.Add(adminUser);
            context.SaveChanges();
        }

        private static void EnsureAdminUsersTable(ApplicationDbContext context)
        {
            if (!context.Database.IsRelational())
            {
                return;
            }

            context.Database.ExecuteSqlRaw(
                """
                CREATE TABLE IF NOT EXISTS a_blue_rainbow_adminusers (
                    \"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    \"Username\" character varying(100) NOT NULL,
                    \"DisplayName\" character varying(150) NOT NULL,
                    \"PasswordHash\" text NOT NULL,
                    \"IsActive\" boolean NOT NULL,
                    \"CreatedAtUtc\" timestamp with time zone NOT NULL
                );
                """);

            context.Database.ExecuteSqlRaw(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS \"IX_a_blue_rainbow_adminusers_Username\"
                ON a_blue_rainbow_adminusers (\"Username\");
                """);
        }

        private static void EnsureAdminAuditLogsTable(ApplicationDbContext context)
        {
            if (!context.Database.IsRelational())
            {
                return;
            }

            context.Database.ExecuteSqlRaw(
                """
                CREATE TABLE IF NOT EXISTS a_blue_rainbow_adminauditlogs (
                    \"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    \"ActorAdminUserId\" integer NULL,
                    \"ActorUsername\" character varying(100) NOT NULL,
                    \"ActionType\" character varying(100) NOT NULL,
                    \"EntityType\" character varying(100) NOT NULL,
                    \"EntityId\" character varying(100) NOT NULL,
                    \"Description\" character varying(400) NOT NULL,
                    \"MetadataJson\" text NULL,
                    \"IpAddress\" character varying(100) NULL,
                    \"UserAgent\" character varying(512) NULL,
                    \"OccurredAtUtc\" timestamp with time zone NOT NULL
                );
                """);

            context.Database.ExecuteSqlRaw(
                """
                CREATE INDEX IF NOT EXISTS \"IX_a_blue_rainbow_adminauditlogs_OccurredAtUtc\"
                ON a_blue_rainbow_adminauditlogs (\"OccurredAtUtc\");
                """);
        }
    }
}
