# Generated by Django 6.0.6 on 2026-07-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(db_index=True, max_length=50)),
                ('facility_name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'a_blue_rainbow_providers',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(db_index=True, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('city', models.CharField(db_index=True, max_length=50, null=True)),
                ('state', models.CharField(db_index=True, max_length=50, null=True)),
                ('zcta', models.BooleanField(null=True)),
                ('parent_zcta', models.CharField(max_length=50, null=True)),
                ('population', models.IntegerField(null=True)),
                ('density', models.FloatField(null=True)),
                ('county_fips', models.IntegerField(null=True)),
                ('county_name', models.CharField(max_length=50, null=True)),
                ('county_weights', models.CharField(max_length=128, null=True)),
                ('county_names_all', models.CharField(max_length=64, null=True)),
                ('county_fips_all', models.CharField(max_length=50, null=True)),
                ('imprecise', models.BooleanField(null=True)),
                ('military', models.BooleanField(null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
                ('state_abbrev', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'a_blue_rainbow_states',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HospiceFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('zip_code', models.CharField(db_index=True, max_length=15)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('medicare_elig', models.BooleanField(default=True, null=True)),
                ('map', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('reviews', models.TextField(null=True)),
                ('official_website', models.CharField(max_length=255, null=True)),
                ('facility_type', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='hospice', to='a_blue_rainbow.provider')),
            ],
            options={
                'db_table': 'a_blue_rainbow_hospicefacilities',
            },
        ),
        migrations.CreateModel(
            name='HomeHealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('zip_code', models.CharField(db_index=True, max_length=15)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('medicare_elig', models.BooleanField(default=True, null=True)),
                ('map', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('reviews', models.TextField(null=True)),
                ('official_website', models.CharField(max_length=255, null=True)),
                ('private_duty_aide', models.BooleanField(default=True, null=True)),
                ('private_duty_nurse', models.BooleanField(default=True, null=True)),
                ('skilled_therapy', models.BooleanField(default=True, null=True)),
                ('transportation_services', models.BooleanField(default=True, null=True)),
                ('case_management', models.BooleanField(default=True, null=True)),
                ('facility_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='home_health', to='a_blue_rainbow.provider')),
            ],
            options={
                'db_table': 'a_blue_rainbow_homehealthfacilities',
            },
        ),
        migrations.CreateModel(
            name='AssistedLivingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('zip_code', models.CharField(db_index=True, max_length=15)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('medicare_elig', models.BooleanField(default=True, null=True)),
                ('map', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('reviews', models.TextField(null=True)),
                ('official_website', models.CharField(max_length=255, null=True)),
                ('transportation_services', models.BooleanField(default=True, null=True)),
                ('case_management', models.BooleanField(default=True, null=True)),
                ('facility_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assisted_living', to='a_blue_rainbow.provider')),
            ],
            options={
                'db_table': 'a_blue_rainbow_assistedlivingfacilities',
            },
        ),
        migrations.CreateModel(
            name='SkilledNursingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('zip_code', models.CharField(db_index=True, max_length=15)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('medicare_elig', models.BooleanField(default=True, null=True)),
                ('map', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('reviews', models.TextField(null=True)),
                ('official_website', models.CharField(max_length=255, null=True)),
                ('transportation_services', models.BooleanField(default=True, null=True)),
                ('case_management', models.BooleanField(default=True, null=True)),
                ('facility_type', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='skilled_nursing', to='a_blue_rainbow.provider')),
            ],
            options={
                'db_table': 'a_blue_rainbow_skillednursingfacilities',
            },
        ),
    ]
