# Generated by Django 4.1.7 on 2023-04-10 22:01
# Generated by Django 4.2 on 2023-04-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zcta', models.BooleanField(null=True)),
                ('parent_zcta', models.CharField(max_length=50, null=True)),
                ('population', models.IntegerField(null=True)),
                ('density', models.FloatField(null=True)),
                ('county_fips', models.IntegerField(null=True)),
                ('county_name', models.CharField(max_length=50, null=True)),
                ('county_weights', models.CharField(max_length=128, null=True)),
                ('county_names_all', models.CharField(max_length=64, null=True)),
                ('county_fips_all', models.CharField(max_length=50, null=True)),
                ('imprecise', models.BooleanField(null=True)),
                ('military', models.BooleanField(null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
                ('state_abbrev', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkilledNursingFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('medicare_elig', models.BooleanField(default=True)),
                ('transportation_services', models.BooleanField(default=True)),
                ('case_management', models.BooleanField(default=True)),
                ('map', models.TextField()),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
                ('official_website', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='skilled_nursing', to='a_blue_rainbow.providers')),
            ],
        ),
        migrations.CreateModel(
            name='HospiceFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('medicare_elig', models.BooleanField(default=True)),
                ('map', models.TextField()),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
                ('official_website', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='hospice', to='a_blue_rainbow.providers')),
            ],
        ),
        migrations.CreateModel(
            name='HomeHealthFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('medicare_elig', models.BooleanField(default=True)),
                ('private_duty_aide', models.BooleanField(default=True)),
                ('private_duty_nurse', models.BooleanField(default=True)),
                ('skilled_therapy', models.BooleanField(default=True)),
                ('transportation_services', models.BooleanField(default=True)),
                ('case_management', models.BooleanField(default=True)),
                ('map', models.TextField()),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
                ('official_website', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='home_health', to='a_blue_rainbow.providers')),
            ],
        ),
        migrations.CreateModel(
            name='AssistedLivingFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('medicare_elig', models.BooleanField(default=True)),
                ('transportation_services', models.BooleanField(default=True)),
                ('case_management', models.BooleanField(default=True)),
                ('map', models.TextField()),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
                ('official_website', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='assisted_living', to='a_blue_rainbow.providers')),
            ],
        ),
    ]
