# Generated by Django 4.2 on 2023-04-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistedLivingFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=15)),
                ("phone_number", models.CharField(max_length=15)),
                ("type", models.CharField(max_length=10)),
                ("medicare_elig", models.BooleanField(default=True)),
                ("transportation_services", models.BooleanField(default=True)),
                ("case_management", models.BooleanField(default=True)),
                ("map", models.TextField()),
                ("rating", models.IntegerField()),
                ("reviews", models.TextField()),
                ("official_website", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HomeHealthFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=15)),
                ("phone_number", models.CharField(max_length=15)),
                ("type", models.CharField(max_length=10)),
                ("medicare_elig", models.BooleanField(default=True)),
                ("private_duty_aide", models.BooleanField(default=True)),
                ("private_duty_nurse", models.BooleanField(default=True)),
                ("skilled_therapy", models.BooleanField(default=True)),
                ("transportation_services", models.BooleanField(default=True)),
                ("case_management", models.BooleanField(default=True)),
                ("map", models.TextField()),
                ("rating", models.IntegerField()),
                ("reviews", models.TextField()),
                ("official_website", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HospiceFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=15)),
                ("phone_number", models.CharField(max_length=15)),
                ("type", models.CharField(max_length=10)),
                ("medicare_elig", models.BooleanField(default=True)),
                ("map", models.TextField()),
                ("rating", models.IntegerField()),
                ("reviews", models.TextField()),
                ("official_website", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Providers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assisted_living",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assisted_living",
                        to="a_blue_rainbow.assistedlivingfacilities",
                    ),
                ),
                (
                    "home_health",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_health",
                        to="a_blue_rainbow.homehealthfacilities",
                    ),
                ),
                (
                    "hospice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospice",
                        to="a_blue_rainbow.hospicefacilities",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkilledNursingFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=15)),
                ("phone_number", models.CharField(max_length=15)),
                ("type", models.CharField(max_length=10)),
                ("medicare_elig", models.BooleanField(default=True)),
                ("transportation_services", models.BooleanField(default=True)),
                ("case_management", models.BooleanField(default=True)),
                ("map", models.TextField()),
                ("rating", models.IntegerField()),
                ("reviews", models.TextField()),
                ("official_website", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="a_blue_rainbow.providers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("comments", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ZipCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=15)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zip_code",
                        to="a_blue_rainbow.states",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="providers",
            name="skilled_nursing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skilled_nursing",
                to="a_blue_rainbow.skillednursingfacilities",
            ),
        ),
    ]
