# Generated by Django 4.2 on 2023-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='population',
            field=models.CharField(null=True),
        ),
    ]
