# Generated by Django 4.2 on 2023-04-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_blue_rainbow", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assistedlivingfacilities",
            old_name="state",
            new_name="state_name",
        ),
        migrations.RenameField(
            model_name="homehealthfacilities",
            old_name="state",
            new_name="state_name",
        ),
        migrations.RenameField(
            model_name="hospicefacilities",
            old_name="state",
            new_name="state_name",
        ),
        migrations.RenameField(
            model_name="skillednursingfacilities",
            old_name="state",
            new_name="state_name",
        ),
    ]
