# Generated by Django 4.2 on 2023-04-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_blue_rainbow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providers",
            name="assisted_living",
        ),
        migrations.RemoveField(
            model_name="providers",
            name="home_health",
        ),
        migrations.RemoveField(
            model_name="providers",
            name="hospice",
        ),
        migrations.RemoveField(
            model_name="providers",
            name="skilled_nursing",
        ),
        migrations.AddField(
            model_name="providers",
            name="type",
            field=models.CharField(default="no string", max_length=50),
            preserve_default=False,
        ),
    ]
