# Generated by Django 4.2 on 2023-04-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("a_blue_rainbow", "0002_remove_providers_assisted_living_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistedlivingfacilities",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assisted_living",
                to="a_blue_rainbow.providers",
            ),
        ),
        migrations.AlterField(
            model_name="homehealthfacilities",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_health",
                to="a_blue_rainbow.providers",
            ),
        ),
        migrations.AlterField(
            model_name="hospicefacilities",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospice",
                to="a_blue_rainbow.providers",
            ),
        ),
        migrations.AlterField(
            model_name="skillednursingfacilities",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skilled_nursing",
                to="a_blue_rainbow.providers",
            ),
        ),
    ]
