# Generated by Django 4.1.7 on 2023-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0002_rename_state_assistedlivingfacilities_state_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
