# Generated by Django 4.2 on 2023-04-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0006_alter_hospicefacilities_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospicefacilities',
            name='map',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='medicare_elig',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='official_website',
            field=models.CharField(default='nostring', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='phone_number',
            field=models.CharField(default='nostring', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='reviews',
            field=models.TextField(default='nostring'),
            preserve_default=False,
        ),
    ]
