# Generated by Django 4.2 on 2023-04-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0007_alter_hospicefacilities_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospicefacilities',
            name='map',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='medicare_elig',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='official_website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospicefacilities',
            name='reviews',
            field=models.TextField(null=True),
        ),
    ]
