# Generated by Django 4.2 on 2023-04-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0008_alter_hospicefacilities_map_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistedlivingfacilities',
            old_name='type',
            new_name='facility_type',
        ),
        migrations.RenameField(
            model_name='homehealthfacilities',
            old_name='type',
            new_name='facility_type',
        ),
        migrations.RenameField(
            model_name='hospicefacilities',
            old_name='type',
            new_name='facility_type',
        ),
        migrations.RenameField(
            model_name='providers',
            old_name='type',
            new_name='facility_type',
        ),
        migrations.RenameField(
            model_name='skillednursingfacilities',
            old_name='type',
            new_name='facility_type',
        ),
    ]
