# Generated by Django 4.2 on 2023-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0009_rename_type_assistedlivingfacilities_facility_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='facility_name',
            field=models.CharField(default='nostring', max_length=255),
            preserve_default=False,
        ),
    ]
