# Generated by Django 4.2 on 2023-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0011_alter_assistedlivingfacilities_facility_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='case_management',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='map',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='medicare_elig',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='official_website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='reviews',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='transportation_services',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='case_management',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='map',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='medicare_elig',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='official_website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='private_duty_aide',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='private_duty_nurse',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='reviews',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='skilled_therapy',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='transportation_services',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='case_management',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='map',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='medicare_elig',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='official_website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='reviews',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='transportation_services',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
