# Generated by Django 4.2 on 2023-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0012_alter_assistedlivingfacilities_case_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistedlivingfacilities',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='homehealthfacilities',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='skillednursingfacilities',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
