# Generated by Django 5.2.14 on 2026-05-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_blue_rainbow', '0013_alter_assistedlivingfacilities_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssistedLivingFacilities',
            new_name='AssistedLivingFacility',
        ),
        migrations.RenameModel(
            old_name='HomeHealthFacilities',
            new_name='HomeHealthFacility',
        ),
        migrations.RenameModel(
            old_name='HospiceFacilities',
            new_name='HospiceFacility',
        ),
        migrations.RenameModel(
            old_name='Providers',
            new_name='Provider',
        ),
        migrations.RenameModel(
            old_name='SkilledNursingFacilities',
            new_name='SkilledNursingFacility',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
        migrations.AlterModelTable(
            name='assistedlivingfacility',
            table='a_blue_rainbow_assistedlivingfacilities',
        ),
        migrations.AlterModelTable(
            name='homehealthfacility',
            table='a_blue_rainbow_homehealthfacilities',
        ),
        migrations.AlterModelTable(
            name='hospicefacility',
            table='a_blue_rainbow_hospicefacilities',
        ),
        migrations.AlterModelTable(
            name='provider',
            table='a_blue_rainbow_providers',
        ),
        migrations.AlterModelTable(
            name='skillednursingfacility',
            table='a_blue_rainbow_skillednursingfacilities',
        ),
        migrations.AlterModelTable(
            name='state',
            table='a_blue_rainbow_states',
        ),
    ]
